export type PhraseLanguage =
    | 'czech'
    | 'english'
    | 'french'
    | 'italian'
    | 'japanese'
    | 'korean'
    | 'portuguese'
    | 'simplifiedChinese'
    | 'spanish'
    | 'traditionalChinese'
