// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetEvmNetworkAddressBalanceData,
  GetEvmNetworkAddressBalanceErrors,
  GetEvmNetworkAddressBalanceResponses,
  GetEvmNetworkAddressHistoryData,
  GetEvmNetworkAddressHistoryErrors,
  GetEvmNetworkAddressHistoryResponses,
  GetEvmNetworkAddressTokenBalancesData,
  GetEvmNetworkAddressTokenBalancesErrors,
  GetEvmNetworkAddressTokenBalancesResponses,
  GetEvmNetworkAddressTransactionCountData,
  GetEvmNetworkAddressTransactionCountErrors,
  GetEvmNetworkAddressTransactionCountResponses,
  GetEvmNetworkBlockByHashData,
  GetEvmNetworkBlockByHashErrors,
  GetEvmNetworkBlockByHashResponses,
  GetEvmNetworkBlockByHeightData,
  GetEvmNetworkBlockByHeightErrors,
  GetEvmNetworkBlockByHeightResponses,
  GetEvmNetworkEstimateGasData,
  GetEvmNetworkEstimateGasErrors,
  GetEvmNetworkEstimateGasResponses,
  GetEvmNetworkFeeRateData,
  GetEvmNetworkFeeRateErrors,
  GetEvmNetworkFeeRateResponses,
  GetEvmNetworkLatestBlockData,
  GetEvmNetworkLatestBlockErrors,
  GetEvmNetworkLatestBlockResponses,
  GetEvmNetworkLogoData,
  GetEvmNetworkLogoErrors,
  GetEvmNetworkLogoResponses,
  GetEvmNetworkNetworkStatusData,
  GetEvmNetworkNetworkStatusErrors,
  GetEvmNetworkNetworkStatusResponses,
  GetEvmNetworkNftMetadataAnimationData,
  GetEvmNetworkNftMetadataAnimationErrors,
  GetEvmNetworkNftMetadataAnimationResponses,
  GetEvmNetworkNftMetadataData,
  GetEvmNetworkNftMetadataErrors,
  GetEvmNetworkNftMetadataImageData,
  GetEvmNetworkNftMetadataImageErrors,
  GetEvmNetworkNftMetadataImageResponses,
  GetEvmNetworkNftMetadataResponses,
  GetEvmNetworkTokenDataData,
  GetEvmNetworkTokenDataErrors,
  GetEvmNetworkTokenDataResponses,
  GetEvmNetworkTokenLogoData,
  GetEvmNetworkTokenLogoErrors,
  GetEvmNetworkTokenLogoResponses,
  GetEvmNetworkTransactionDetailsData,
  GetEvmNetworkTransactionDetailsErrors,
  GetEvmNetworkTransactionDetailsResponses,
  GetGlobalLogoNetworkData,
  GetGlobalLogoNetworkErrors,
  GetGlobalLogoNetworkResponses,
  GetGlobalMarketsData,
  GetGlobalMarketsErrors,
  GetGlobalMarketsResponses,
  GetGlobalNetworksInfoData,
  GetGlobalNetworksInfoErrors,
  GetGlobalNetworksInfoResponses,
  GetUtxoNetworkAddressBalanceData,
  GetUtxoNetworkAddressBalanceErrors,
  GetUtxoNetworkAddressBalanceResponses,
  GetUtxoNetworkAddressHistoryData,
  GetUtxoNetworkAddressHistoryErrors,
  GetUtxoNetworkAddressHistoryResponses,
  GetUtxoNetworkBlockByHashData,
  GetUtxoNetworkBlockByHashErrors,
  GetUtxoNetworkBlockByHashResponses,
  GetUtxoNetworkBlockByHeightData,
  GetUtxoNetworkBlockByHeightErrors,
  GetUtxoNetworkBlockByHeightResponses,
  GetUtxoNetworkFeeRateData,
  GetUtxoNetworkFeeRateErrors,
  GetUtxoNetworkFeeRateResponses,
  GetUtxoNetworkLatestBlockData,
  GetUtxoNetworkLatestBlockErrors,
  GetUtxoNetworkLatestBlockResponses,
  GetUtxoNetworkLogoData,
  GetUtxoNetworkLogoErrors,
  GetUtxoNetworkLogoResponses,
  GetUtxoNetworkMempoolData,
  GetUtxoNetworkMempoolErrors,
  GetUtxoNetworkMempoolResponses,
  GetUtxoNetworkTransactionDetailsData,
  GetUtxoNetworkTransactionDetailsErrors,
  GetUtxoNetworkTransactionDetailsResponses,
  GetUtxoNetworkUtxosByAddressData,
  GetUtxoNetworkUtxosByAddressErrors,
  GetUtxoNetworkUtxosByAddressResponses,
  PostEvmNetworkBroadcastTransactionData,
  PostEvmNetworkBroadcastTransactionErrors,
  PostEvmNetworkBroadcastTransactionResponses,
  PostEvmNetworkCallSmartContractFunctionData,
  PostEvmNetworkCallSmartContractFunctionErrors,
  PostEvmNetworkCallSmartContractFunctionResponses,
  PostRpcNetworkData,
  PostRpcNetworkErrors,
  PostRpcNetworkResponses,
  PostUtxoNetworkBroadcastTransactionData,
  PostUtxoNetworkBroadcastTransactionErrors,
  PostUtxoNetworkBroadcastTransactionResponses,
  PostUtxoNetworkEstimateTransactionSizeData,
  PostUtxoNetworkEstimateTransactionSizeErrors,
  PostUtxoNetworkEstimateTransactionSizeResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get address balance
 *
 * Returns the confirmed and unconfirmed native balance for an EVM address.
 */
export const getEvmNetworkAddressBalance = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkAddressBalanceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkAddressBalanceResponses,
    GetEvmNetworkAddressBalanceErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/addressBalance',
    ...options,
  });

/**
 * Get address history
 *
 * Returns paginated transaction history for an EVM address, including decoded contract events (transfers, mints, approvals, etc.)
 */
export const getEvmNetworkAddressHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkAddressHistoryData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkAddressHistoryResponses,
    GetEvmNetworkAddressHistoryErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/addressHistory',
    ...options,
  });

/**
 * Get address token balances
 *
 * Returns all ERC-20/ERC-721/ERC-1155 token balances for an EVM address. Uses an ephemeral Solidity contract executed via eth_call to batch-inspect all contracts the address has interacted with. Token metadata is enriched from TrustWallet and on-chain sources. Requires the Meteorex indexer to be available for the network.
 */
export const getEvmNetworkAddressTokenBalances = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkAddressTokenBalancesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkAddressTokenBalancesResponses,
    GetEvmNetworkAddressTokenBalancesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/addressTokenBalances',
    ...options,
  });

/**
 * Get address transaction count
 *
 * Returns the nonce (transaction count) for an EVM address
 */
export const getEvmNetworkAddressTransactionCount = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkAddressTransactionCountData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkAddressTransactionCountResponses,
    GetEvmNetworkAddressTransactionCountErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/addressTransactionCount',
    ...options,
  });

/**
 * Get block by hash
 *
 * Returns block details for the given block hash
 */
export const getEvmNetworkBlockByHash = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkBlockByHashData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkBlockByHashResponses,
    GetEvmNetworkBlockByHashErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/blockByHash',
    ...options,
  });

/**
 * Get block by height
 *
 * Returns block details for the given block height
 */
export const getEvmNetworkBlockByHeight = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkBlockByHeightData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkBlockByHeightResponses,
    GetEvmNetworkBlockByHeightErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/blockByHeight',
    ...options,
  });

/**
 * Broadcast transaction
 *
 * Broadcasts a signed raw transaction to the network
 */
export const postEvmNetworkBroadcastTransaction = <ThrowOnError extends boolean = false>(
  options: Options<PostEvmNetworkBroadcastTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostEvmNetworkBroadcastTransactionResponses,
    PostEvmNetworkBroadcastTransactionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/broadcastTransaction',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Call smart contract function
 *
 * Executes a read-only (eth_call) call against a smart contract
 */
export const postEvmNetworkCallSmartContractFunction = <ThrowOnError extends boolean = false>(
  options: Options<PostEvmNetworkCallSmartContractFunctionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostEvmNetworkCallSmartContractFunctionResponses,
    PostEvmNetworkCallSmartContractFunctionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/callSmartContractFunction',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Estimate gas
 *
 * Estimates the gas required for a transaction
 */
export const getEvmNetworkEstimateGas = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkEstimateGasData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkEstimateGasResponses,
    GetEvmNetworkEstimateGasErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/estimateGas',
    ...options,
  });

/**
 * Get fee rate estimates
 *
 * Returns fee rate estimates for 4 priority tiers. EIP-1559 networks return maxFeePerGas/maxPriorityFeePerGas, legacy networks return gasPrice
 */
export const getEvmNetworkFeeRate = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkFeeRateData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkFeeRateResponses,
    GetEvmNetworkFeeRateErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/feeRate',
    ...options,
  });

/**
 * Get latest block
 *
 * Returns the latest block number and hash for the specified EVM network
 */
export const getEvmNetworkLatestBlock = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkLatestBlockData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkLatestBlockResponses,
    GetEvmNetworkLatestBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/latestBlock',
    ...options,
  });

/**
 * Get network logo
 *
 * Returns the SVG logo for the specified EVM network. The response is an SVG image.
 */
export const getEvmNetworkLogo = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkLogoData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetEvmNetworkLogoResponses, GetEvmNetworkLogoErrors, ThrowOnError>(
    {
      security: [
        {
          in: 'query',
          name: 'api_key',
          type: 'apiKey',
        },
      ],
      url: '/evm/{network}/logo',
      ...options,
    },
  );

/**
 * Get network status
 *
 * Returns current network status including block time, gas usage, and fee predictions
 */
export const getEvmNetworkNetworkStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkNetworkStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkNetworkStatusResponses,
    GetEvmNetworkNetworkStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/networkStatus',
    ...options,
  });

/**
 * Get token data
 *
 * Returns metadata and on-chain information for a token contract, including name, symbol, decimals, total supply, detected token standard (ERC-20/ERC-721/ERC-1155), and logo. Works on all supported EVM networks without requiring a wallet address.
 */
export const getEvmNetworkTokenData = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkTokenDataData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkTokenDataResponses,
    GetEvmNetworkTokenDataErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/tokenData',
    ...options,
  });

/**
 * Get token logo
 *
 * Returns the logo image for a token contract on the specified EVM network. The response is a binary image (PNG or SVG).
 */
export const getEvmNetworkTokenLogo = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkTokenLogoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkTokenLogoResponses,
    GetEvmNetworkTokenLogoErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/tokenLogo',
    ...options,
  });

/**
 * Get transaction details
 *
 * Returns detailed information about a transaction by its hash
 */
export const getEvmNetworkTransactionDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkTransactionDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkTransactionDetailsResponses,
    GetEvmNetworkTransactionDetailsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/transactionDetails',
    ...options,
  });

/**
 * Get NFT metadata
 *
 * Returns the full decoded metadata for a specific NFT token, including name, description, image, animation URL, external URL, and attributes. Fetches the tokenURI from the contract (ERC-721 tokenURI or ERC-1155 uri), then resolves and decodes the metadata JSON. Supports HTTPS, data: (base64), and IPFS URIs. Results are cached in Redis.
 */
export const getEvmNetworkNftMetadata = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkNftMetadataData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkNftMetadataResponses,
    GetEvmNetworkNftMetadataErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/nft/metadata',
    ...options,
  });

/**
 * Get NFT animation
 *
 * Returns the animation or video for a specific NFT token as binary data. Resolves the animation_url from the NFT metadata (supports IPFS, HTTPS, and data: URIs) and proxies it through ChainGate so consumers don't need to handle IPFS resolution. The response content type matches the original format.
 */
export const getEvmNetworkNftMetadataAnimation = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkNftMetadataAnimationData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkNftMetadataAnimationResponses,
    GetEvmNetworkNftMetadataAnimationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/nft/metadata/animation',
    ...options,
  });

/**
 * Get NFT image
 *
 * Returns the image for a specific NFT token as binary data. Resolves the image URL from the NFT metadata (supports IPFS, HTTPS, and data: URIs) and proxies the image through ChainGate so consumers don't need to handle IPFS resolution. The response content type matches the original image format.
 */
export const getEvmNetworkNftMetadataImage = <ThrowOnError extends boolean = false>(
  options: Options<GetEvmNetworkNftMetadataImageData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEvmNetworkNftMetadataImageResponses,
    GetEvmNetworkNftMetadataImageErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/evm/{network}/nft/metadata/image',
    ...options,
  });

/**
 * Get market data
 *
 * Returns cryptocurrency prices and fiat exchange rates for all supported networks, including many beyond those with dedicated /evm or /utxo endpoints (e.g. Mantle, Celo, Moonbeam, Berachain, etc.)
 */
export const getGlobalMarkets = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalMarketsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetGlobalMarketsResponses, GetGlobalMarketsErrors, ThrowOnError>({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/global/markets',
    ...options,
  });

/**
 * Get networks info
 *
 * Returns real-time information for all supported EVM networks, including many that don't have dedicated /evm endpoints (e.g. Mantle, Celo, Moonbeam, Berachain, etc.). Includes block times, gas usage, and fee predictions.
 */
export const getGlobalNetworksInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalNetworksInfoData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetGlobalNetworksInfoResponses,
    GetGlobalNetworksInfoErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/global/networksInfo',
    ...options,
  });

/**
 * Get network logo
 *
 * Returns the SVG logo for any supported network, including networks beyond those with dedicated /evm or /utxo endpoints (e.g. Mantle, Celo, Moonbeam, Berachain, etc.). The response is an SVG image.
 */
export const getGlobalLogoNetwork = <ThrowOnError extends boolean = false>(
  options: Options<GetGlobalLogoNetworkData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetGlobalLogoNetworkResponses,
    GetGlobalLogoNetworkErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/global/logo/{network}',
    ...options,
  });

/**
 * JSON-RPC endpoint
 *
 * Executes JSON-RPC calls against the specified blockchain network.
 */
export const postRpcNetwork = <ThrowOnError extends boolean = false>(
  options: Options<PostRpcNetworkData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostRpcNetworkResponses, PostRpcNetworkErrors, ThrowOnError>({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/rpc/{network}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get address balance
 *
 * Returns the confirmed and unconfirmed balance for a UTXO address
 */
export const getUtxoNetworkAddressBalance = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkAddressBalanceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkAddressBalanceResponses,
    GetUtxoNetworkAddressBalanceErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/addressBalance',
    ...options,
  });

/**
 * Get address history
 *
 * Returns paginated transaction history for a UTXO address
 */
export const getUtxoNetworkAddressHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkAddressHistoryData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkAddressHistoryResponses,
    GetUtxoNetworkAddressHistoryErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/addressHistory',
    ...options,
  });

/**
 * Get block by hash
 *
 * Returns block details for the given block hash
 */
export const getUtxoNetworkBlockByHash = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkBlockByHashData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkBlockByHashResponses,
    GetUtxoNetworkBlockByHashErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/blockByHash',
    ...options,
  });

/**
 * Get block by height
 *
 * Returns block details for the given block height
 */
export const getUtxoNetworkBlockByHeight = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkBlockByHeightData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkBlockByHeightResponses,
    GetUtxoNetworkBlockByHeightErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/blockByHeight',
    ...options,
  });

/**
 * Broadcast transaction
 *
 * Broadcasts a signed raw transaction to the UTXO network
 */
export const postUtxoNetworkBroadcastTransaction = <ThrowOnError extends boolean = false>(
  options: Options<PostUtxoNetworkBroadcastTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostUtxoNetworkBroadcastTransactionResponses,
    PostUtxoNetworkBroadcastTransactionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/broadcastTransaction',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Estimate transaction size
 *
 * Estimates the byte size of a transaction given inputs and outputs
 */
export const postUtxoNetworkEstimateTransactionSize = <ThrowOnError extends boolean = false>(
  options: Options<PostUtxoNetworkEstimateTransactionSizeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostUtxoNetworkEstimateTransactionSizeResponses,
    PostUtxoNetworkEstimateTransactionSizeErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/estimateTransactionSize',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get fee rate estimates
 *
 * Returns fee rate estimates for 4 priority tiers in satoshis per KB
 */
export const getUtxoNetworkFeeRate = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkFeeRateData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkFeeRateResponses,
    GetUtxoNetworkFeeRateErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/feeRate',
    ...options,
  });

/**
 * Get latest block
 *
 * Returns the latest block number and hash for the specified UTXO network
 */
export const getUtxoNetworkLatestBlock = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkLatestBlockData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkLatestBlockResponses,
    GetUtxoNetworkLatestBlockErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/latestBlock',
    ...options,
  });

/**
 * Get network logo
 *
 * Returns the SVG logo for the specified UTXO network. The response is an SVG image.
 */
export const getUtxoNetworkLogo = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkLogoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkLogoResponses,
    GetUtxoNetworkLogoErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/logo',
    ...options,
  });

/**
 * Get mempool
 *
 * Returns paginated mempool transaction IDs
 */
export const getUtxoNetworkMempool = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkMempoolData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkMempoolResponses,
    GetUtxoNetworkMempoolErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/mempool',
    ...options,
  });

/**
 * Get transaction details
 *
 * Returns detailed information about a transaction by its ID
 */
export const getUtxoNetworkTransactionDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkTransactionDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkTransactionDetailsResponses,
    GetUtxoNetworkTransactionDetailsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/transactionDetails',
    ...options,
  });

/**
 * Get UTXOs by address
 *
 * Returns paginated unspent transaction outputs for a UTXO address
 */
export const getUtxoNetworkUtxosByAddress = <ThrowOnError extends boolean = false>(
  options: Options<GetUtxoNetworkUtxosByAddressData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUtxoNetworkUtxosByAddressResponses,
    GetUtxoNetworkUtxosByAddressErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'query',
        name: 'api_key',
        type: 'apiKey',
      },
    ],
    url: '/utxo/{network}/utxosByAddress',
    ...options,
  });
